#debug: true

spring:
  datasource:
    # 连接数据库的url
    url: jdbc:mysql://localhost:3306/coding_first?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    # 连接数据库的账号
    username: root
    #  连接数据库的密码
    password: wyx

logging:
  config: classpath:conf/logback-dev-spring.xml

com:
  fjut:
    cf:
      localJudgePath: http://localhost:8100
      baseFilePath: /app/file/
      baseJudgeFilePath: /app/judge_system/judge_file/data/
      picPath: pic/
      picVerifyPath: pic/verify/