#debug: true

spring:
  datasource:
    # 连接数据库的url
    url: jdbc:mysql://localhost:3306/cf_test?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    # 连接数据库的账号
    username: root
    #  连接数据库的密码
    password: wyx
  # 邮件配置
  mail:
    host: smtp.qq.com
    username: axiangcoding@foxmail.com
    password: uqjuaxkpcfzgdgbi


logging:
  config: classpath:conf/logback-dev-spring.xml

cf:
  config:
    swagger:
      enable: true
    druid:
      name: admin
      pwd: admin
    localJudgePath: http://192.168.122.129:8100
    baseFilePath: D://
    baseJudgeFilePath: D://test_data/
    picPath: pic/
    picVerifyPath: pic/verify/